version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: pm-backend
    ports:
      - 8080:8080
    restart: always
    command: http-server . --cors

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: pm-frontend
    ports:
      - 3000:3000
    restart: always
    command: npm start
